/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const PostCategory = IDL.Variant({
  'jobs' : IDL.Null,
  'latest' : IDL.Null,
  'cultural' : IDL.Null,
  'tribalTales' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'membershipBadge' : IDL.Text,
  'avatar' : IDL.Text,
});
export const JobPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'image' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'likes' : IDL.Nat,
  'timestamp' : IDL.Int,
  'mediaType' : MediaType,
  'category' : PostCategory,
});
export const TribalTale = IDL.Record({
  'id' : IDL.Nat,
  'introVideo' : IDL.Bool,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Tribalpreneur = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Text,
  'businessName' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text], [], []),
  'addJobPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPost' : IDL.Func(
      [IDL.Text, IDL.Text, MediaType, PostCategory, IDL.Text],
      [],
      [],
    ),
  'addTribalTale' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'addTribalpreneur' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getJobPosts' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
  'getPostsByCategory' : IDL.Func([PostCategory], [IDL.Vec(Post)], ['query']),
  'getTribalTales' : IDL.Func([], [IDL.Vec(TribalTale)], ['query']),
  'getTribalpreneurs' : IDL.Func([], [IDL.Vec(Tribalpreneur)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'seedData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null });
  const PostCategory = IDL.Variant({
    'jobs' : IDL.Null,
    'latest' : IDL.Null,
    'cultural' : IDL.Null,
    'tribalTales' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'membershipBadge' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const JobPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'image' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'likes' : IDL.Nat,
    'timestamp' : IDL.Int,
    'mediaType' : MediaType,
    'category' : PostCategory,
  });
  const TribalTale = IDL.Record({
    'id' : IDL.Nat,
    'introVideo' : IDL.Bool,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Tribalpreneur = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Text,
    'businessName' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text], [], []),
    'addJobPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPost' : IDL.Func(
        [IDL.Text, IDL.Text, MediaType, PostCategory, IDL.Text],
        [],
        [],
      ),
    'addTribalTale' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'addTribalpreneur' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getJobPosts' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
    'getPostsByCategory' : IDL.Func([PostCategory], [IDL.Vec(Post)], ['query']),
    'getTribalTales' : IDL.Func([], [IDL.Vec(TribalTale)], ['query']),
    'getTribalpreneurs' : IDL.Func([], [IDL.Vec(Tribalpreneur)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'seedData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };