/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface JobPost {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'company' : string,
  'image' : string,
}
export type MediaType = { 'video' : null } |
  { 'image' : null };
export interface Post {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : string,
  'likes' : bigint,
  'timestamp' : bigint,
  'mediaType' : MediaType,
  'category' : PostCategory,
}
export type PostCategory = { 'jobs' : null } |
  { 'latest' : null } |
  { 'cultural' : null } |
  { 'tribalTales' : null };
export interface TribalTale {
  'id' : bigint,
  'introVideo' : boolean,
  'name' : string,
  'role' : string,
}
export interface Tribalpreneur {
  'id' : bigint,
  'owner' : string,
  'businessName' : string,
  'description' : string,
  'image' : string,
}
export interface UserProfile {
  'isPremium' : boolean,
  'name' : string,
  'role' : string,
  'membershipBadge' : string,
  'avatar' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string], undefined>,
  'addJobPost' : ActorMethod<[string, string, string, string], undefined>,
  'addPost' : ActorMethod<
    [string, string, MediaType, PostCategory, string],
    undefined
  >,
  'addTribalTale' : ActorMethod<[string, string, boolean], undefined>,
  'addTribalpreneur' : ActorMethod<[string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getJobPosts' : ActorMethod<[], Array<JobPost>>,
  'getPostsByCategory' : ActorMethod<[PostCategory], Array<Post>>,
  'getTribalTales' : ActorMethod<[], Array<TribalTale>>,
  'getTribalpreneurs' : ActorMethod<[], Array<Tribalpreneur>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, string, string, boolean],
    undefined
  >,
  'seedData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];